### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by dnaq** [sodiumoxide/sodiumoxide#203]
Call for maintainers
====================

Since I haven't had time to maintain sodiumoxide lately, I think it is time for
someone else to take the reins. There are some outstanding pull-requests and
open issues and even though sodiumoxide is usable as is, I feel bad for
everyone contributing when I don't have time to merge, or even look at, their
changes.

In this document I'll try to explain the background and philosophy of
sodiumoxide and also what I'm looking for in a maintainer.

Background
----------

When I started to learn rust (back in the 0.x days, when pointers still had
sigils) I decided to implement a network service as my learner project. For
that service I needed some cryptographic functionality, so I made some bindings
to libsodium since the cryptographic ecosystem of rust was basically
non-existent at the time.

After a while I realized that good, and easy to use, cryptographic bindings
were something that the whole rust community could make use of. Also, by making
one of the first cryptographic libraries for rust consist of relatively safe
primitives there was an opportunity to make other rust projects keep a higher
cryptographic standard than in many other languages. This might sound
far-fetched, but in my experience many developers unfamiliar with an API will
read the documentation and experiment until they have something that seems to
work. The main issue of course is that in cryptography something that seems to
work can still fail in catastrophic ways. I believe the right solution for that
is to make the APIs as fool-proof as possible, and NaCl/libsodium has done a
lot of work in exposing those kinds of APIs.

The main box/secretbox abstraction is a really nice one, and even though it
doesn't protect against misuse of nonces, the abstraction protects against a
lot of potential errors. This can be contrasted to just giving a programmer
without cryptographic experience raw access to block ciphers, cipher modes,
MACs, asymmetric cipher and hope that they will magically combine these
primitives into something secure.

By making it easy to use secure primitives in rust, my hope was that authors
looking to use cryptography would default to using these primitives.

A bindings library per-se isn't that big of an achievement, but I saw no
need in reimplementing NaCl in rust at the time. This might be a fun future
project idea though.

Philosophy
----------

The basic philosophy of sodiumoxide is the same as of NaCl. Expose secure and
easy to use primitives by default. The main goal isn't to implement all
possible cryptographic primitives or to be able to implement something like TLS
using sodiumoxide.

Another important part of the philosophy is to not add primitives and
functionality that hasn't been proven secure (or isn't part of the
cryptographic literature). An example of this is the key-conversion
functionality between curve25519 and ed25519 keys that has been requested
multiple times. Since there is no literature proving that dual-use of keys for
both key derivation and signing is secure I haven't added that functionality.

I prefer the maintainer to subscribe to the same philosophy. We can add
functionality as long as we don't create new potential foot-guns for the users
of the library.

Tasks for a maintainer
----------------------

For all open issues and pull-requests:
    - For each issue, decide if it's something that should be added
    - Do a thorough code review of all changes
    - Make sure that the code follows the coding style in the project
    - Make sure that the code contains thorough tests
    - Merge the code into the master branch

I'm also looking for someone that can communicate with the community.

Future Directions
-----------------

### Add new functionality from libsodium

This is of course contingent on the functionality being compatible with our philosophy.

### Try to make sodiumoxide usable on embedded systems

Make sure that the library can work without dynamic memory allocations, that we can build it with xargo and so on.

### Use bindgen to create `libsodium-sys` instead of handwriting it

This hasn't been done yet since bindgen has an open bug where it messes up constness of pointers.

### Choice of static compilation of libsodium-sys

There have been some pull-requests that automatically download and build
libsodium as part of the build of sodiumoxide.  This is something that would
help a lot of users, but I have been concerned about verifying the authenticity
of the libsodium download. This functionality is contingent on being able to
solve the download issue in a secure way.

Transition Plan
---------------

1. First I will see if anyone wants to maintain the library at all, if not then it might be time to deprecate it.
2. If I find someone suitable I will discuss the issue with them
3. We will then decide if I should grant commit access to the repository of if they should fork the repository (effectively moving it).
4. During a transition period the maintainer will need to ask me to make a new release
    - I will review the diff and discuss it with the maintainer
    - If I'm happy a new release will be pushed to crates.io
5. After a transition period I will hand over access to crates.io to the new maintainer.

Discussion
----------

Any questions about the search for a new maintainer are directed to this thread.

**Comment by Dylan-DPC** [comment]
Hi @dnaq 
Do check out: https://users.rust-lang.org/t/bus-factor-1-for-crates/17046/22

We are willing to help you maintain this and set this up for a team to maintain.

**Comment by dnaq** [comment]
@Dylan-DPC Thanks for the offer, that sounds like just what I'm looking for.

**Comment by dnaq** [comment]
@Dylan-DPC how does this work. Will you suggest a maintainer?

**Comment by Dylan-DPC** [comment]
@dnaq We don't have many maintainers in the rust bus organisation so right now it will be either me and/or @kornel. Will create a post and an organisation so we can move the repo there.

**Comment by Tom-Phinney** [comment]
@dnaq @Dylan-DPC Although I'm fairly new to Rust, I was once a mathematician, have a modest crypto employment background, and have studied the NaCl code base. I don't have enough experience with Rust and its tooling to take on the full maintenance task but I believe that I could be a substantial contributor to the process.

**Comment by dnaq** [comment]
@Tom-Phinney Your background seems to be really suitable for co-maintaining this project. Do you have any links to any online presence of yours?, (code you've written, related work).

**Comment by Dylan-DPC** [comment]
hey @Tom-Phinney 

That's fine. It is good to have someone who knows cryptography well. Even if you are a beginner at rust, it is okay we will help you

**Comment by samscott89** [comment]
I'd be keen on becoming a co-maintainer as well. I've done a couple of Rust libs (but none as popular as sodiumoxide) --  see [libpasta](github.com/libpasta) for example.
My background is in crypto as well, so can help on that side of things as well.

**Comment by Dylan-DPC** [comment]
@Tom-Phinney @samscott89 okay cool. I have sent you invites to the organisation.

**Comment by dnaq** [comment]
The repository is now moved to the sodiumoxide organization and it feels really good to have two cryptographers onboard as co-maintainers. I'll hold on to the crates.io account for a while, but after a couple of successful releases I'll add the organization to the crate as well. Thanks for stepping up everyone, looking forward to the next release.

**Comment by Kornel** [comment]
@Dylan-DPC you mentioned me, but I think you must have meant someone else :-)

**Comment by Dylan-DPC** [comment]
@Kornel Nah. I mentioned you earlier thinking you might want to join us as being part of rust bus. Its fine :smile:

**Comment by nvesely** [comment]
I was wondering why the docs stopped working. Guess this answers my question.

I would actually like to join the bus factor for this crate if possible. My background is a math bachelor's (with two undergraduate theses related to cryptography) followed by 3 years in the information security industry. I'm starting an Information Security master's program in September. I've only known Rust for a number of months, but have worked on a few cryptography projects in that time.

I'm currently using SodiumOxide in a one-time signature scheme implementation I'm working on.

**Comment by kinggoesgaming** [comment]
I love how @Dylan-DPC quietly didn’t mention me ... :P

**Comment by kinggoesgaming** [comment]
@dnaq should this be considered resolved for now? If so I think its a good idea to close this issue

**Comment by dnaq** [comment]
I’ll let one of the new maintainers close the issue, feels more appropriate.

**Comment by nvesely** [comment]
I didn't get a response before you closed this, but I'm still interested in helping to maintain this repo.

**Comment by Dylan-DPC** [comment]
Oops @nvesely. Will add you to the organization

**Comment by nvesely** [comment]
Awesome!

**Comment by nvesely** [comment]
I joined the organization, but that doesn't make me a repo maintainer or add me to the bors reviewers list. If you could set that when you get the chance @Dylan-DPC -- thanks.

**Comment by Dylan-DPC** [comment]
Yah will give you all that don't worry

**Comment by naftulikay** [comment]
How can I help?

**Comment by naftulikay** [comment]
@Dylan-DPC As a user of the library, I'm a bit familiar with the source code, and I have fairly good knowledge of applied cryptography, etc. Not sure where or how I could help, but willing and able :)

**Comment by Dylan-DPC** [comment]
@naftulikay great. will add you to the organisation, repo and gitter

**Comment by kpcyrd** [comment]
I have a couple of projects that depend on sodiumoxide, if you're still looking for help I would be interested in joining.

**Comment by nvesely** [comment]
@kpcyrd I'm on-board with you joining. We already have a lot of maintainers, but that's a good thing IMO.

**Comment by Dylan-DPC** [comment]
@nvesely, @kinggoesgaming is open to stepping down as a co-maintainer because he isn't able to devote time to the repo. So we can swap him with @kpcyrd

**Comment by nvesely** [comment]
Sgtm!

**Comment by naftulikay** [comment]
FWIW I'm also not able to devote much time to it, other than providing
advice on API decisions and applied crypto stuff. I was overly optimistic
about my time constraints when I joined. I don't necessarily want to leave
the project, but I figured I'd be honest here.

**Comment by Dylan-DPC** [comment]
@naftulikay That's fine. We are moving slowly on this repo so we don't need to a lot of involvement. Just a review whenever you can should be enough :+1:

**Comment by Dylan-DPC** [comment]
I've added @kpcyrd to the organisation :+1:

**Comment by kpcyrd** [comment]
Awesome, thank you :)

**Comment by nvesely** [comment]
@naftulikay You should at least be following the repo though :smiling_imp:

**Comment by naftulikay** [comment]
My bad, refollowed.
