### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by dnaq** [sodiumoxide/sodiumoxide#219]
We have had some pretty big pull requests lately, especially now that we create libsodium-sys with bindgen instead of manually. Maybe it's time for a new release?

Does anyone want to merge anything more before I push the crate?

**Comment by kinggoesgaming** [comment]
None of current open PRs are unable position to be immediately merged in so it's a 👍 from me

**Comment by Dylan-DPC** [comment]
Yeah definitely. However, i would like to have a 0.1 release sometime soon. @dnaq do you see anything that's pending for a 0.1?

**Comment by dnaq** [comment]
We could do a 0.1, but before a 1.0 I would like to stabilize the api as
much as possible, e.g.

Do everything in the same way, make sure that we have non-allocating
versions of all primitives, make sure that we can build on embedded without
std (and add Travis tests for those cases), use sane serde serialization
instead of the current hack (since we can’t derive for large byte arrays),
use descriptive error types and so on and so forth.

**Comment by Dylan-DPC** [comment]
Yeah. 1.0 is still a long way to go. Just wanted to do a 0.1 release so we can promise more stability.

**Comment by dnaq** [comment]
0.1.0 is now pushed to crates.io

**Comment by Dylan-DPC** [comment]
@dnaq it is better to publish after the release PR is merged. Also we need to create a github release before merging.

**Comment by Dylan-DPC** [comment]
Created the [release](https://github.com/sodiumoxide/sodiumoxide/releases/tag/0.1.0).

**Comment by dnaq** [comment]
@Dylan-DPC You are correct, I just wouldn't have the opportunity to publish the crate for a week or so if I didn't publish it yesterday.
