### ISSUE TITLE
Could not compile v0.1.0 on Windows 

### ISSUE THREAD

**Issue by kpp** [sodiumoxide/sodiumoxide#223]
Have a look at this build: https://ci.appveyor.com/project/kpp/tox/build/1.0.1654
Commit: https://github.com/tox-rs/tox/commit/93f989a54b

Fixes https://github.com/tox-rs/tox/pull/160

**Comment by Dylan-DPC** [comment]
@kpp Thanks for reporting this issue. We will look into it.

**Comment by kpp** [comment]
You may use our [Appveyor config](https://github.com/tox-rs/tox/blob/master/.appveyor.yml) to setup CI

**Comment by Dylan-DPC** [comment]
@kpp do you mind sending a PR? :stuck_out_tongue:

**Comment by kpp** [comment]
Sure. Register your project at https://appveyor.com/ to allow github use webhooks to trigger CI buils

**Comment by Dylan-DPC** [comment]
@kpp done :

**Comment by kpp** [comment]
Fixed.
