### ISSUE TITLE
feature: decrementing Nonce or gen_mid_nonce()

### ISSUE THREAD

**Issue by kac-** [sodiumoxide/sodiumoxide#224]
For two way communication ever i.e. secretbox it's crucial to avoid nonce collision when incrementing nonce scheme is used. Current solution for second-party would be i.e. to feed pre-made slice (with half of slice set to `0xff` and second half to `0x00`) into `Nonce::from_slice` (we cannot just set MSB in the slice because we don't know whether `from_slice` is BE or LE).
In my opinion lack of built-in solution unnecessarily leaves users' apps prone to implementation errors.
It would be nice to have either:
`decrement_le()`
or
`gen_zero_nonce()` and `gen_mid_nonce()`

**Comment by jedisct1** [comment]
That would be very clunky.

Don't reinvent the wheel. The key exchange function (`crypto_kx`) returns a pair of shared keys. Use one in one direction, the other one in the other direction.

And unless ordering is not important, just use `crypto_secretstream`, so you don't have to worry about nonces or key rotation.

**Comment by kac-** [comment]
@jedisct1 I'm new to rust, read wrong docs https://docs.rs/exonum_sodiumoxide/0.0.20/exonum_sodiumoxide/ (no crypto_kx there), partially because [docs link from crates.io](https://docs.rs/sodiumoxide/0.1.0/sodiumoxide/) `does not exist` and so do https://sodiumoxide.github.io/.
`crypto_secretstream` will suite me best (from libsodium docs I see that I can calculate ciphertext length from plaintext length, am I right?)  but I don't see it in *sodiumoxide* yet, thankfully there's a PR with it.

**Comment by Dylan-DPC** [comment]
@kac- yeah there is some issue with `cargo doc` atm. you can check the 0.1.0 docs [here](https://docs.rs/crate/sodiumoxide/0.1.0)
