### ISSUE TITLE
Investigate potential problems with bindgen

### ISSUE THREAD

**Issue by nvesely** [sodiumoxide/sodiumoxide#232]
@Fraser999 wrote:

> 1. I found that bindgen didn't work by default on Windows.  I had to install Clang (libclang.dll had to be available), and even then I hit further problems which forced me on to Ubuntu as being the path of least resitance to running bindgen.  It looks like [this](https://github.com/sodiumoxide/sodiumoxide/pull/225#issuecomment-400641946) is a similar cross-platform issue. (the compiler is picking up the VS headers in favour of the MinGW ones, and adding a `-isystem <path to AppVeyor's MinGW includes>` to the flags might fix it?)  However, a more pressing issue was that I found I needed to [tweak the generated source code](https://github.com/Fraser999/rust_sodium/blob/master/rust_sodium-sys/src/lib.rs#L44-L50):
>     1. The biggest issue; bindgen didn't apply the required `#[repr(align(...))]`.  Fortunately, we experienced a [CI test failure on AppVeyor](https://ci.appveyor.com/project/MaidSafe-QA/rust-sodium/build/1.0.291/job/8ne8k8htv36ik4yp) which exposed the undefined behaviour, resulting in head-scratching, soul-searching and eventually [this commit](https://github.com/maidsafe/rust_sodium/pull/60/commits/13b90978247a5f6e520c1b1b21ded66a14e3c353).  I guess bindgen should handle this now that rust stable does, but I haven't checked on that.  If bindgen doesn't, I suppose it could be added to the build script, but that would be somewhat of a hack!
>     1. bindgen provided bindings to functions flagged deprecated.
>     1. there was an [issue with pointer constness](https://github.com/rust-lang-nursery/rust-bindgen/issues/511), but it's now been resolved.

It would be good to

- Confirm that the following sub-bullets are not affecting sodiumoxide:
  - [ ] i
  - [ ] ii
  - [ ] iii
- [ ] See how we might address building on Windows preferably without tweaking the generated code. This might include documenting additional dependencies for the platform or making upstream changes to bindgen.

**Comment by Ralith** [comment]
Requiring libclang.so at build time is pretty onerous in general. My distro doesn't even package libclang as a dynamic library.

**Comment by dbrgn** [comment]
The libclang requirement broke my tests: https://github.com/dbrgn/threema-gateway-rs/pull/19 While that can easily be fixed, it will also break the tests/builds of all downstream crates (as long as libclang is not installed). I'm not yet sure whether I want that. Would there be a possibility to get rid of that requirement?

**Comment by Dylan-DPC** [comment]
@dbrgn sorry but no updates yet. Was busy getting some other work sorted on the repo. If you have any suggestions, feel free to let us know how you think we can solve this.

**Comment by Ralith** [comment]
Why not run bindgen manually and commit the generated code, like every other rust -sys crate?

**Comment by kpp** [comment]
> Why not run bindgen manually and commit the generated code, like every other rust -sys crate?

I agree. I hate build deps like `clang.so` or `bindgen`.

@dnaq @Dylan-DPC @kurnevsky What are pros and cons of generating bindings on the fly?

**Comment by kpp** [comment]
Fixed in https://github.com/sodiumoxide/sodiumoxide/pull/281
