### ISSUE TITLE
Rustfmt

### ISSUE THREAD

**Issue by nvesely** [sodiumoxide/sodiumoxide#235]
`cargo fmt --all -- --check` should run in a Travis matrix build with a pinned nightly version and builds should fail when . The nightly should be pinned because:

1. the version of Rust determines the version of rustfmt when installing via the standard `rustup component add rustfmt-preview`
2. if you don't pin a nightly then:
  1. in order to pass CI you might have to let rustfmt modify code you didn't touch, making for an unclear diff.
  2. it will randomly turn out the `master` branch is "broken" if you re-run the CI when a new nightly/rustfmt version comes out.

The pinned nightly should be periodically updated. We should document in a `CONTRIBUTING.md` as well as in a [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) that the author should have run rustfmt and that they should not include a separate rustfmt commit which will clog up our git history. The PR template can include a lil' checkbox they should tick to indicate they're code has been formatted with the correct nightly.

**Comment by Dylan-DPC** [comment]
We don't need to pin rustfmt to a nightly. The problem with pinned version is that it is dificult to expect everyone to be on the same version. We have been  using the latest nightly on the uuid crate and we didn't face much issues with the banking on the latest nightly.

Yeah there are few instances where rustfmt has a new rule or is broken and changes the formatting of the entire codebase. In those cases, we or the author can push a separate PR that changes it to match the latest rustfmt.

**Comment by nvesely** [comment]
There should be a rustfmt bot that checks master daily and makes a PR if necessary lol. I’m fine with not pinning, but have gotten complaints before about having to keep re-running it during extended PR processes where it updated multiple times. Also the diffs. But it’s almost a non-issue, so let’s not ¯\_(ツ)_/¯

**Comment by Dylan-DPC** [comment]
We have been following the latest-nightly-fmt for uuid and haven't had any issues so far. I think it is best to stick to that as we are already testing on latest nightly and it is easier to get people to use the latest nightly than pin them to a certain build and expect them to update when we update. Yeah it's a non-issue.
