### ISSUE TITLE
Test suite improvement

### ISSUE THREAD

**Issue by darrenldl** [sodiumoxide/sodiumoxide#241]
This is largely a checklist for me to keep track of what tests(property tests, test vectors, etc) to add, but also useful in case someone else wants to add tests but avoid duplicate work.

Still in process of adding new items.

- [ ] `crypto/pwhash/scryptsalsa208sha256.rs`
  - [ ] `prop_test`
    - [ ] `pwhash_verify` should always verify `pwhash` successfully
    - [ ] `pwhash_verify` should always **fail** when verifying `pwhash` if any corruption is present
- [ ] `crypto/onetimeauth/poly1305.rs`
  - [ ] test vectors
    - [ ] https://tools.ietf.org/html/rfc7539
- [ ] `crypto/auth/hmacsha*.rs`
  - [ ] test vectors
    - [ ] https://tools.ietf.org/html/rfc4231
- [ ] `crypto/box_/curve25519xsalsa20poly1305.rs`
  - [ ] `prop_test`
    - [ ] sealing then opening should produce same plaintext

**Comment by kpp** [comment]
This seems like a good candidate to make a PR from. I would love to see you filing a PR.

Feel free to open a new issue if you think we are missing something.
