### ISSUE TITLE
Failure while cross compiling for Android armv7

### ISSUE THREAD

**Issue by vu3rdd** [sodiumoxide/sodiumoxide#242]
I am trying to cross compile a project that depends on `sodiumoxide`. Since I will be need to load my project via JNI, I am building a dynamic library. I get a linking failure that the `libsodium.so` could not be found. I have reproduced it by cross compiling `sodiumoxide` (instead of my project that depends on it) with the following diff applied for building a dynamic library.
```
diff --git a/Cargo.toml b/Cargo.toml
index 1ea8a794..b4bd15d5 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -34,3 +34,6 @@ quickcheck = "^0.6.2"
 benchmarks = []
 std = []
 default = ["serde", "std"]
+
+[lib]
+crate-type = ["dylib"]
```
I invoke the Android cross compiler as follows:

```
env CC_armv7-linux-androideabi=arm-linux-androideabi-gcc PKG_CONFIG_ALLOW_CROSS=1  cargo build  --target armv7-linux-androideabi --release
```

The error I get is this:
```
error: linking with `/home/ram/work/android/ndk-rust/ndk/arm/bin/arm-linux-androideabi-clang` failed: exit code: 1
```
I have pasted the full error here: https://lpaste.net/3059302713859768320
Has anyone else got an experience with this sort of an error? I could perhaps work around by compiling libsodium separately and placing the shared library somewhere on the search path of the cross compiler/linker. If that is the only way, then perhaps I could file a wishlist bug against `cargo` to improve cross compilation experience for the libraries that depend on C libraries. a better way. Any help is appreciated! Thanks.

**Comment by vu3rdd** [comment]
OK, so cross compiling libsodium separately and dropping the `.so` file into the `target/release/deps` directory made the error go away.

**Comment by kinggoesgaming** [comment]
This should be on the TODO list for Na2O CI story

**Comment by kpp** [comment]
@vu3rdd would you please test it again?

```
cd sodiumoxide
git pull
git checkout static_bindings
# unset SODIUM* variables
```

And use this(https://github.com/maidsafe/rust_sodium#cross-compiling-for-arm) guide to crosscompile for armv7?

**Comment by kpp** [comment]
It failed.

```
sudo apt install gcc-arm-linux-androideabi
rustup target add armv7-linux-androideabi
```

.cargo/config :
```
[target.armv7-linux-androideabi]
linker = "gcc-arm-linux-androideabi"
```

```
cargo build --target armv7-linux-androideabi
...
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c: In function 'crypto_box_curve25519xsalsa20poly1305_messagebytes_max':
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c:155:12: error: 'SIZE_MAX' undeclared (first use in this function)
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c:155:12: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
crypto_box/crypto_box.c: In function 'crypto_box_messagebytes_max':
crypto_box/crypto_box.c:55:12: error: 'SIZE_MAX' undeclared (first use in this function)
```


We need more investigations.

**Comment by kpp** [comment]
The best way to start is  https://github.com/jedisct1/libsodium/blob/master/dist-build/android-armv7-a.sh , https://github.com/jedisct1/libsodium/blob/master/dist-build/android-build.sh . I am not an android dev, it will be hard for me to debug it.

**Comment by kpp** [comment]
We have released a new version of sodiumoxide. See https://github.com/sodiumoxide/sodiumoxide#cross-compiling-for-armv7-unknown-linux-musleabihf-via-docker for crosscompilation
