### ISSUE TITLE
Meeting #1 

### ISSUE THREAD

**Issue by Dylan-DPC** [sodiumoxide/sodiumoxide#251]
Tracker issue for 1st Meeting:

This issue will cover everything regarding the meeting from finalising the timings to what is discussed in the meeting.

**Comment by Dylan-DPC** [comment]
@sodiumoxide/owners Do pick your preferred timings for the meeting on [doodle](https://doodle.com/poll/ka2m4in6vdgbaxsc) so we can finalise a time slot for the meeting. 

Other collaborators and watchers are welcome as well. 

PS: Posted here as well in case some of you don't check gitter.

**Comment by darrenldl** [comment]
I assume I'll leave it blank as I can't make it?

**Comment by Dylan-DPC** [comment]
@darrenldl yeah or there is a "not attending" or some similar button iirc

**Comment by Dylan-DPC** [comment]
@sodiumoxide/owners The meeting is scheduled for 26th September 1630 UTC. 

## Agenda: 
* Current state of the crate 
* Existing issues / PRs
* Improving the maintainance of the repo
* What more do we need  for 0.1.1 / 0.2.0

**Comment by Dylan-DPC** [comment]
# Notes from the meeting:

### Current Issues

**Problems with current PRs (and PR process)**: 
1 The secretstream API isn't finished yet
2. A lot of the pull requests don't have comprehensive tests
3. break the coding style of the rest of the library
4. #188, #237 needs more tests 
5. #239 A cursory overview reviews some mistakes, e.g. a mutable pointer cast from a const pointer to a non-mutable object
and it would be nice if we kept the exact same api as in crypto::pwhash::scrypt
and the test situation is pretty weak
6. but if the code is reviewed, the api could be fixed (probably by splitting it into two variants, crypto::pwhash::argon2id13 and crypto::pwhash::argon2i13 with clear documentation on what the differences are)
and with comprehensive added tests it could be merged
gist: https://gist.github.com/dnaq/a61a4b3b8d150bb57977144e9138159f
7. #252: not needed. rust has the hex-crate

**TODO**:
1.  create a CONTRIBUTING.md detailing what is needed to contribute to sodiumoxide, and in the future close all pull-requests/alert the user if he is missing anything
2. #200 can be merged after testing on windows 
3. fix appveyor config by taking from https://github.com/ceph3us/sodiumoxide

### Plans for Future: 
1.  break compatibility for 0.2.0. Would prefer to remove crypto::*box::(seal|open)_detached and make detached the default behaviour
2. Release (0.1.1) with  pull-requests we want to merge (after all fixes) and a better windows experience (vcpkg, appveyor) + Contributing file
3. have a release by end of this year just to get things moving forward 

### Crate Maintenance: 
1. 2 separate reviews on each PR - one from a rust perspective and the other from a crypto perspective. I'm thinking of creating 2 teams for that so that it's easier to ping the right group that is needed for the review
2.  switch to edition 2018 when it's released. A unstable 2018 branch till 1.30 is stable in December (2018 ed release)

### Debian packaging of libsodium: 
1. Debian-Rust team has some tooling for that and most of it is automated, Mostly there isn't much that needs to be done from an upstream point of view, besides making sure that all dependencies are up2date and not deprecated
2. libsodium-sys is going to depend on libsodium-dev in debian
3. better to wait for https://github.com/sodiumoxide/sodiumoxide/issues/234#issuecomment-414797999 to be implemented before doing the debian release
4. We can't depend on anything from the network (network is going to be unavailable during the build) so everything needs to be selfcontained or use something that's already in debian
if there's code that downloads the libsodium we would have to patch that out
5. For debian it (depending on libsodium) isn't an issue, the libsodium-sys deb will depend on libsodium-dev, and the sodiumoxide deb will depend on the libsodium-sys deb
6. bump bindgen to a newer version

### Misc:: 
1. target minimum libsodium version for 0.1.1 (end of year), windows compatibility fixes by first quarter of 2019 (0.1.2 / 0.2.0)
2. Existing issues will be used for hacktoberfest
