### ISSUE TITLE
error: hex2bin more strictly aligned

### ISSUE THREAD

**Issue by kpp** [sodiumoxide/sodiumoxide#286]
Output of `cargo clippy`:

```
error: casting from `*mut u8` to a more-strictly-aligned pointer (`*mut *const i8`)
   --> src/utils.rs:113:13
    |
113 |             hex_end as *mut _,
    |             ^^^^^^^^^^^^^^^^^
    |
    = note: #[deny(clippy::cast_ptr_alignment)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#cast_ptr_alignment

error: aborting due to previous error
```

https://rust-lang.github.io/rust-clippy/master/index.html#cast_ptr_alignment

> Dereferencing the resulting pointer may be **undefined behavior**.

@lovesh need your help

**Comment by kpp** [comment]
Seems like we have to use https://doc.rust-lang.org/std/ffi/struct.CStr.html

**Comment by dnaq** [comment]
This is completely broken. hex_end should be a pointer to a pointer, so it’s not just an alignment issue, this is memory unsafe code.

**Comment by dnaq** [comment]
We should remove hex2bin and bin2hex completely from the repo until someone has time to do a fix.

Are these functions part of the latest release? If so we should push a new release ASAP, otherwise we could wait.

**Comment by kpp** [comment]
I have already found a fix https://github.com/sodiumoxide/sodiumoxide/pull/288  . I need to know how idiomatic bindings to these functions should look like.

**Comment by kpp** [comment]
> Are these functions part of the latest release?

No

**Comment by dnaq** [comment]
Another question is how can we improve our processes so that we won’t make such a mistake again. Of course running clippy is a good first step, but here we have failed with our code reviews and test coverage.
