### ISSUE TITLE
Update to libsodium 1.0.17

### ISSUE THREAD

**Issue by kurnevsky** [sodiumoxide/sodiumoxide#305]
Libsodium 1.0.17 is out: https://github.com/jedisct1/libsodium/releases/tag/1.0.17

**Comment by Dylan-DPC** [comment]
Thanks. Are you ready to create a PR? you have to change the version in [this file](https://github.com/sodiumoxide/sodiumoxide/blob/c348a2c531faa993aa7384224951e8681eca72ba/libsodium-sys/build.rs#L25)
