### ISSUE TITLE
Expose `AsRef<[u8]>` for all newtypes

### ISSUE THREAD

**Issue by mbelop** [sodiumoxide/sodiumoxide#321]
Hi,

According to the [libsodium documentation](https://docs.rs/sodiumoxide/0.2.1/sodiumoxide/crypto/kx/index.html#usage):

> These keys can be used by any functions requiring secret keys up to crypto_kx_SESSIONKEYBYTES bytes, including crypto_secretbox_*() and crypto_aead_*().

Therefore at least the AsRef trait must be implemented for the SessionKey type to be able to convert it to the `secretbox::Key` (or `secretstream::Key` in my use case). Otherwise it looks like once SessionKey is generated, there's nothing that can be done with it. Please correct me if I'm wrong here.

As far as I can tell this is because implementation of SessionKey is generated via a "secret" key macro.  Should it be "public" instead?

Cheers,
Mike

**Comment by dnaq** [comment]
I believe that the long term solution would be to implement AsRef<[u8]> for all types that wrap byte arrays. The short term solution for you would probably be to use the index implementation to get a slice containing the data you are interested in, e.g. &sessionkey[..]

**Comment by mbelop** [comment]
Thanks for the tip regarding the Index trait, I was going the long way of `bincode::serialize` and `bincode::deserialize` into the other key type.
