### ISSUE TITLE
Allow building from source without downloading

### ISSUE THREAD

**Issue by pcrockett** [sodiumoxide/sodiumoxide#328]
This is prompted by #326, but I think it's a legitimate feature idea even if #326 was not getting in my way.

I would like to avoid downloading libsodium from scratch when building libsodium-sys. Of course this is possible using the `SODIUM_LIB_DIR` environment variable, and it's a relatively easy scenario for Windows because a pre-compiled lib is actually provided by the libsodium project.

However it seems that for Unix-like systems to avoid downloading the source code during the build, they would need to manually build libsodium separately to generate their own lib files, which is a bit more of a hassle. Especially for cross-platform projects that need to build on multiple operating systems.

It would be awfully nice to be able to specify an environment variable like `SODIUM_SRC_DIR` or something like that, and have the build script use that directory instead of downloading the code every time or forcing users to supply their own lib files. This would enable me to take advantage of Git submodules to retrieve the libsodium source, or a local mirror of the libsodium project, for example.

I might be able to submit a PR myself, if you think this is a good idea.

**Comment by pcrockett** [comment]
Ah. Should have checked the list of pending pull requests. #300 would address this.

**Comment by Dylan-DPC** [comment]
Closing this as duplicate. Thanks
