### ISSUE TITLE
Unable to build a HashedPassword using from_slice out of a valid hash

### ISSUE THREAD

**Issue by Keirua** [sodiumoxide/sodiumoxide#340]
Hi, 
I'm following the doc on https://docs.rs/sodiumoxide/0.2.2/sodiumoxide/crypto/pwhash/index.html regarding how to perform hash verification: hashing a password in order to feed it to pwhash_verify, using a hash stored in a file for comparison.

In the following minimalistic example (sodiumoxide = "0.2.1"), reloading a hash from a file using HashPassword::from_slice returns None, where from what I understand I should return a HashedPassword. Am I doing something wrong, or is there something missing in the documentation?

```rust
extern crate sodiumoxide;

use sodiumoxide::crypto::pwhash::scryptsalsa208sha256::OPSLIMIT_INTERACTIVE;
use sodiumoxide::crypto::pwhash::scryptsalsa208sha256::MEMLIMIT_INTERACTIVE;
use sodiumoxide::crypto::pwhash::scryptsalsa208sha256::pwhash;
use sodiumoxide::crypto::pwhash::argon2i13::HashedPassword;
use sodiumoxide::crypto::pwhash::argon2i13::pwhash_verify;

fn main() {
    let password = b"plop";

    let hashed_password = pwhash(
        password,
        OPSLIMIT_INTERACTIVE,
        MEMLIMIT_INTERACTIVE
    );

    let original_hashed_bytes = hashed_password.as_ref().unwrap();
    std::fs::write("hash", original_hashed_bytes).expect("unable to write hash file");

    let data_from_file = std::fs::read("hash").expect("Unable to read hash file");
    let hash_from_file = HashedPassword::from_slice(&data_from_file[..]);

    println!("hashed_bytes");
    println!("{:?}", original_hashed_bytes); // [36, 55, 36, 67, 54…]
    println!("hashed_bytes");
    println!("{:?}", &data_from_file[..]); // [36, 55, 36, 67, 54…]
    println!("hash");
    println!("{:?}", hash_from_file); // None :( instead of HashedPassword([36, 55, 36, 67, 54…])
}
```

**Comment by kpp** [comment]
> from_slice() creates an object from a byte slice

> This function will fail and return None if the length of the byte-slice isn't equal to the length of the object

Please ensure you got the same length.

**Comment by Keirua** [comment]
ok it makes sense, I was making a scryptsalsa208sha256 hash and trying to convert it back into an argon2i13 hash, so it couldn't work. Ha, automatic imports…

"the length of the object" could be clarified (I'll make a PR) into explaining it's about the expected size of the hash, right now it's not clear what length we are talking about (it was not to me, until I read the code).
