### ISSUE TITLE
Bump libsodium-sys

### ISSUE THREAD

**Issue by jean-airoldie** [sodiumoxide/sodiumoxide#352]
So that crates can use the metadata added in #344.

**Comment by kpp** [comment]
We will do this soon. There is a fix in #356 which requires rustc 1.36. Are you ok with it?

**Comment by jean-airoldie** [comment]
Yep

**Comment by jean-airoldie** [comment]
Ping

**Comment by kpp** [comment]
Can we cut a new release?

**Comment by jean-airoldie** [comment]
I don't understand what that means. I don't mind if the libsodium version gets bumped also, if that's what your referring to.

**Comment by kpp** [comment]
https://crates.io/crates/libsodium-sys
