### ISSUE TITLE
Support for bare-metal compilation

### ISSUE THREAD

**Issue by ryankurte** [sodiumoxide/sodiumoxide#363]
hi hi

at the moment compilation depends on libc (and std as in #197) which is not defined for all architectures.

i've had a go at [moving from libc to cty](https://github.com/sodiumoxide/sodiumoxide/compare/master...ryankurte:fix/arm-none-eabi?expand=1) which solves part of the problem (though is v roughly implemented), though something appears to be something wrong with PIC/PIE outputting relocatable code (maybe related to https://github.com/jedisct1/libsodium/issues/677, see also: https://github.com/rust-embedded/cortex-m-rt/issues/22).

this results in: 
```
  = note: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: error: no memory region specified for loadable section `.got'
          collect2: error: ld returned 1 exit status
```
at the final linking stage. i'm setting `SODIUM_DISABLE_PIE=1` and hardcoding `--no-pie` and `-static` as `CFLAGS` in [libsodium-sys/src/build.rs](https://github.com/sodiumoxide/sodiumoxide/compare/master...ryankurte:fix/arm-none-eabi?expand=1#diff-03b86c4d158daab101ab51fd64460e9bR232) but i'm basically out of ideas.

as an aside, have you considered moving to building with cc instead of via autotools to simplify all this? i've done this in cmake before and it wasn't too complex (see also: https://github.com/sodiumoxide/sodiumoxide/issues/377, https://github.com/sodiumoxide/sodiumoxide/pull/379, https://github.com/sodiumoxide/sodiumoxide/pull/406)

**Comment by ryankurte** [comment]
Possibly related to https://github.com/fortanix/rust-mbedtls/pull/63, no solution as yet </3

**Comment by kpp** [comment]
> have you considered moving to building with cc instead of via autotools to simplify all this?

I suggest you ask jedisct1 whether it's possible

**Comment by jedisct1** [comment]
[As documented](https://doc.libsodium.org/installation#cross-compiling), all you need is `--specs=nosys.specs` in the linker flags.

**Comment by ryankurte** [comment]
Unfortunately this does not appear to be the case, I have fixed a bunch of the `sodiumoxide` specific issues in #422 however no combination of `LDFLAGS=--specs=nosys.specs` or `--disable-pie` appears to have any effect on the behaviour of `./configure`.

Running against #442 with:
```
SODIUM_DISABLE_PIE=1 LDFLAGS='--specs=nosys.specs' SODIUM_HOST=arm-none-eabi cargo build --target thumbv7em-none-eabihf
```

Then inserting logging and a panic in `libsodium_src/build.rs` to show the `./configure` and build invocations

`build.rs`:
```
Using CFLAGS: -O0 -ffunction-sections -fdata-sections -g -fno-omit-frame-pointer -mthumb -mfloat-abi=hard -march=armv7e-m -mfpu=fpv4-sp-d16 -Wall -Wextra
Using LDFLAGS: --specs=nosys.specs
```

`./configure`:
```
...
checking whether C compiler accepts -O0 -ffunction-sections -fdata-sections -g -fno-omit-frame-pointer -mthumb -mfloat-abi=hard -march=armv7e-m -mfpu=fpv4-sp-d16 -Wall -Wextra -fvisibility=hidden -fPIC -fno-strict-aliasing -fno-strict-overflow -mno-avx512f... no
...
Failed to configure libsodium using "/home/ryan/projects/dsf-stm-sensor/target/thumbv7em-none-eabihf/debug/build/libsodium-sys-3238d5be2da3c686/out/source/libsodium/configure" "--disable-pie" "--prefix=/home/ryan/projects/dsf-stm-sensor/target/thumbv7em-none-eabihf/debug/build/libsodium-sys-3238d5be2da3c686/out/installed" "--libdir=/home/ryan/projects/dsf-stm-sensor/target/thumbv7em-none-eabihf/debug/build/libsodium-sys-3238d5be2da3c686/out/installed/lib" "--host=arm-none-eabi" "--enable-shared=no"
```

`arm-none-eabi-gcc`:
```
libtool: compile:  arm-none-eabi-gcc -DPACKAGE_NAME=\"libsodium\" -DPACKAGE_TARNAME=\"libsodium\" -DPACKAGE_VERSION=\"1.0.18\" "-DPACKAGE_STRING=\"libsodium 1.0.18\"" -DPACKAGE_BUGREPORT=\"https://github.com/jedisct1/libsodium/issues\" -DPACKAGE_URL=\"https://github.com/jedisct1/libsodium\" -DPACKAGE=\"libsodium\" -DVERSION=\"1.0.18\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_C_VARARRAYS=1 -DLT_OBJDIR=\".libs/\" -DNATIVE_LITTLE_ENDIAN=1 -DHAVE_INLINE_ASM=1 -DASM_HIDE_SYMBOL=.hidden -DHAVE_WEAK_SYMBOLS=1 -DCPU_UNALIGNED_ACCESS=1 -DHAVE_ATOMIC_OPS=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_GETPID=1 -DHAVE_EXPLICIT_BZERO=1 -DCONFIGURED=1 -I. -I./include/sodium -I./include/sodium -O0 -ffunction-sections -fdata-sections -g -fno-omit-frame-pointer -mthumb -mfloat-abi=hard -march=armv7e-m -mfpu=fpv4-sp-d16 -Wall -Wextra -fvisibility=hidden -fPIC -fno-strict-aliasing -fno-strict-overflow -MT crypto_pwhash/argon2/libavx512f_la-argon2-fill-block-avx512f.lo -MD -MP -MF crypto_pwhash/argon2/.deps/libavx512f_la-argon2-fill-block-avx512f.Tpo -c crypto_pwhash/argon2/argon2-fill-block-avx512f.c -o crypto_pwhash/argon2/libavx512f_la-argon2-fill-block-avx512f.o
```

So configure is definitely still picking up `-fPIC` from _somewhere_

**Comment by ryankurte** [comment]
It appears the version of libsodium contained in this repo () contains a `configure` file, patching to remove [L7021](https://github.com/jedisct1/libsodium/blob/b69159b5f89b95930fb162a75bb3854f62eb536a/configure#L7021) stops `-fPIC` being included. As far as I can see that line checks whether `-fPIC` is available and then, applies it?

**Comment by ryankurte** [comment]
I also tried patching `libsodium_sys/build.rs` to forward `--enable-pie=no` instead of `--disable-pie` based on the internals of the `libsodium/configure` file, this appears to have no effect.

```diff
--- a/libsodium-sys/build.rs
+++ b/libsodium-sys/build.rs
@@ -259,7 +259,7 @@ fn make_libsodium(target: &str, source_dir: &Path, install_dir: &Path) -> PathBu
         configure_cmd.env("LDFLAGS", &ldflags);
     }
     if env::var("SODIUM_DISABLE_PIE").is_ok() {
-        configure_cmd.arg("--disable-pie");
+        configure_cmd.arg("--enable-pie=no");
     }
     let configure_status = configure_cmd
         .current_dir(&source_dir)
```

**Comment by jedisct1** [comment]
The latest `1.0.18-stable` version disables PIE/PIC/SP/async-unwind for the `eabi` target, if it can help.

**Comment by adamreichold** [comment]
> The latest `1.0.18-stable` version disables PIE/PIC/SP/async-unwind for the `eabi` target, if it can help.

c.f. #420

**Comment by ryankurte** [comment]
i'm not sure what the detection for `eabi` is but does this also cover the `eabihf` case? (looking at the [commit](https://github.com/jedisct1/libsodium/commit/e04088d0b29f3d9f4575cb6d9c16b93a00bd1041) it would seem to depend whether this is derived from `HOST` or the compiler name?)

**Comment by ryankurte** [comment]
Opened a PR expanding the match from `eabi` to `eabi*` which gets us building with only the additional `sodiumoxide` modifications in #422, thanks for the comments / attention.
