### ISSUE TITLE
Error building on mac 10.14.6

### ISSUE THREAD

**Issue by Ben-Lichtman** [sodiumoxide/sodiumoxide#364]
I get a large error message and fail when trying to build on mac 10.14.6

It appears to by trying to link against linux *.a libraries instead of the mac *.dylib

I have attached the run output here:
[output.txt](https://github.com/sodiumoxide/sodiumoxide/files/3555594/output.txt)

**Comment by Ben-Lichtman** [comment]
Workaround is to use pkg_config with SODIUM_USE_PKG_CONFIG=1 or point libsodium at my library, but would prefer the normal build to work

**Comment by kpp** [comment]
> It appears to by trying to link against linux *.a libraries instead of the mac *.dylib

I think .a files are static libs even in Mac. There should be an issue somewhere else.

**Comment by kpp** [comment]
From output.txt:

> ld: warning: ignoring file ../../src/libsodium/.libs/libsodium.a, file was built for archive which is not the architecture being linked (x86_64): ../../src/libsodium/.libs/libsodium.a

**Comment by kpp** [comment]
https://github.com/sodiumoxide/sodiumoxide/blob/70bd89401c351f3853985be02033570a29e0766c/libsodium-sys/build.rs#L164

@jedisct1 should we check for target `x86_64-apple-darwin` and set vars from https://github.com/jedisct1/libsodium/blob/master/dist-build/osx.sh ?

**Comment by jedisct1** [comment]
That shouldn't be necessary. That script is just here to build redistributable precompiled libraries that work on old versions of macOS.

In all other cases, on macOS like on other Unixish platforms `./configure --prefix=... && make check && make install` should be enough.

**Comment by kpcyrd** [comment]
Closing since this issue has been inactive for quite a while and it seems the question has been answered, please reach out if this issue needs to be reopened!
