### ISSUE TITLE
Add `kdf` functionality

### ISSUE THREAD

**Issue by GallagherCommaJack** [sodiumoxide/sodiumoxide#365]
Libsodium has a module for `kdf` separately from `pwhash` using `blake2b`. For completeness it probably makes sense to bind to it. I've already forked to start work in including it, you can find the commit [here](https://github.com/kalix-systems/sodiumoxide/commit/1449c40ec5eaf3edba3b4521f5ae0b502baa4712).

**Comment by kpp** [comment]
See https://github.com/sodiumoxide/sodiumoxide/pull/351

**Comment by tasn** [comment]
Can this be closed since #351 has been merged?

**Comment by kpp** [comment]
Fixed in https://github.com/sodiumoxide/sodiumoxide/pull/351
