### ISSUE TITLE
Header `version.h` missing for windows builds

### ISSUE THREAD

**Issue by jean-airoldie** [sodiumoxide/sodiumoxide#370]
The [libsodium header](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium.h) links to `sodium/version.h` which only exists if the library was compiled by `./configure` since it requires template substitution of [version.h.in](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/version.h.in). This means that one cannot build on windows and link to the header.

To circumvent this, we could provided a valid `sodium/version.h` file directly in the [tarball](https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/libsodium-1.0.18.tar.gz) along with the `version.h.in`. However, the version number in this file would have to be bumped with each new `libsodium` version.

**Comment by jean-airoldie** [comment]
Here is an example for this file for `1.0.18`:
```c

#ifndef sodium_version_H
#define sodium_version_H

#include "export.h"

#define SODIUM_VERSION_STRING "1.0.18"

#define SODIUM_LIBRARY_VERSION_MAJOR 10
#define SODIUM_LIBRARY_VERSION_MINOR 3


#ifdef __cplusplus
extern "C" {
#endif

SODIUM_EXPORT
const char *sodium_version_string(void);

SODIUM_EXPORT
int         sodium_library_version_major(void);

SODIUM_EXPORT
int         sodium_library_version_minor(void);

SODIUM_EXPORT
int         sodium_library_minimal(void);

#ifdef __cplusplus
}
#endif

#endif
```

**Comment by kpp** [comment]
> However, the version number in this file would have to be bumped with each new libsodium version.

That's not an issue at all. This tarball is provided by jedisct1. The issue is much much deeper than you think.

**Comment by jedisct1** [comment]
It's in `builds/msvc/version.h`.

**Comment by kpcyrd** [comment]
Closing since this issue has been inactive for quite a while and it seems the question has been answered, please reach out if this issue needs to be reopened!
