### ISSUE TITLE
Why AES GCM is missing?

### ISSUE THREAD

**Issue by z0mbie42** [sodiumoxide/sodiumoxide#374]
Hi,

It appears that the only AEAD available primitive is `ChaCha20-Poly1305`, but libsodium have also the more mainstream `AES-GCM-256` (https://libsodium.gitbook.io/doc/secret-key_cryptography/aead/aes-256-gcm).

Why it is missing in this binding?

**Comment by kpcyrd** [comment]
I assume it's either because the GCM has certain limitations that make it much more difficult to get right for sodiumoxide users that chacha20-poly1305 doesn't have, or simply because nobody bothered implementing the bindings yet.

**Comment by z0mbie42** [comment]
Thank you for the response!

**Comment by klittlepage** [comment]
For anyone hitting this thread now this was subsequently addressed in https://github.com/sodiumoxide/sodiumoxide/pull/418.
