### ISSUE TITLE
Cross compilation to x86_64-pc-windows-gnu fails with "undefined reference to __stack_chk_fail"

### ISSUE THREAD

**Issue by adityapk00** [sodiumoxide/sodiumoxide#386]
The final binary fails to link with the following error: 
```
/usr/bin/x86_64-w64-mingw32-ld: /opt/zecwallet-light-cli/target/x86_64-pc-windows-gnu/debug/deps/liblibsodium_sys-104bf71d7ec40bae.rlib(libsodium_la-aead_chacha20poly1305.o):aead_chacha20poly1305.c:(.text+0x161): undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: /opt/zecwallet-light-cli/target/x86_64-pc-windows-gnu/debug/deps/liblibsodium_sys-104bf71d7ec40bae.rlib(libsodium_la-aead_chacha20poly1305.o):aead_chacha20poly1305.c:(.text+0x392): undefined reference to `__stack_chk_fail'
```

Here's my docker file:
```
FROM rust:1.38
LABEL Description="Rust compile env for Linux + Windows (cross)"

RUN apt update
RUN apt install -y build-essential mingw-w64 

RUN rustup target add x86_64-pc-windows-gnu

# Append the linker to the cargo config for Windows cross compile
RUN echo "[target.x86_64-pc-windows-gnu]" >> /usr/local/cargo/config && \
    echo "linker = '/usr/bin/x86_64-w64-mingw32-gcc'" >> /usr/local/cargo/config
```

Note that the building of the crates `sodiumoxide` and `libsodium-sys` succeeds, but the final binary linking step fails.

**Comment by kpp** [comment]
Try to use https://github.com/sodiumoxide/sodiumoxide#extended-usage and precompiled libs from https://download.libsodium.org/libsodium/releases/

**Comment by adityapk00** [comment]
Thanks for the tip! I ended up using the precompiled mingw library and used `SODIUM_LIB_DIR` which worked great. 

Maybe add this to the docs in the `README.md`? Shall I make a PR?

**Comment by kpp** [comment]
There is already such a section in the readme: https://github.com/sodiumoxide/sodiumoxide#using-precompiled-library

**Comment by adityapk00** [comment]
Thanks! I did read through the README before filing this bug, and it wasn't clear that cross compilation for mingw is currently not working, and that we should be using a pre-compiled lib. Google wasn't helpful either. Especially because of this sentence at the top: `... it is highly recommended to use the default way with the pinned version ...`

Maybe add a sentence like "For x86_64-pc-windows-gnu cross compilation, please use a pre-compiled library instead of compiling by hand" 

Then again, maybe Google will index this bug and save future trouble for other people that run into the same issue. 

Thanks for all your help. :smile: :+1:

**Comment by kpp** [comment]
It's definitely a bug. We will fix it.

**Comment by zonyitoo** [comment]
What's the status of this issue? It is not fixed yet. @kpp

**Comment by kpp** [comment]
@sodiumoxide/owners ^
