### ISSUE TITLE
Confusing SODIUM_USE_PKG_CONFIG behavior on msvf

### ISSUE THREAD

**Issue by gdesmott** [sodiumoxide/sodiumoxide#411]
`SODIUM_USE_PKG_CONFIG` [secretly uses](https://github.com/sodiumoxide/sodiumoxide/blob/546e8f21faf51931ebc99000210e06125011486d/libsodium-sys/build.rs#L94) `vcpkg` if the MSVC toolchain is selected which is pretty counter intuitive looking at the name of this variable.

cc @sdroege

**Comment by adamreichold** [comment]
cc #406

**Comment by kpp** [comment]
See https://github.com/sodiumoxide/sodiumoxide#extended-usage, it is a documented behavior.

**Comment by sdroege** [comment]
That it's documented doesn't make it right ;) The way how it is right now it's not possible to use pkg-config on Windows, which can be a bit problematic.

**Comment by kpcyrd** [comment]
`SODIUM_USE_PKG_CONFIG` was introduced to allow dynamic linking using pkg-config. Before that sodiumoxide would either compile a vendored version of libsodium or you had to use `SODIUM_SHARED` which expects you to configure the path manually with `SODIUM_LIB_DIR`.

Windows support was added eventually. This seems to be a minor naming issue, feel free to propose a better one, although we need to keep `SODIUM_USE_PKG_CONFIG` as an alias so we don't break existing projects.

Same applies to the `use-pkg-config` feature that is passed through to `libsodium-sys/use-pkg-config`.

**Comment by dnaq** [comment]
Closing due to deprecation of the library.
