### ISSUE TITLE
Provide point conversion functions in kx

### ISSUE THREAD

**Issue by HoOngEe** [sodiumoxide/sodiumoxide#412]
To utilize key exchange algorithm `X25519` for the keys generated from `Ed25519`, libsodium provides two functions `int crypto_sign_ed25519_pk_to_curve25519` and `int crypto_sign_ed25519_sk_to_curve25519`.
However, these functions are not exposed in `sodiumoxide`. I think it's good to place the corresponding rust binding functions in `kx` module.

**Comment by kpp** [comment]
> Thanks for the pull request. Unfortunately I’ve closed pull requests adding this functionality more times than I can count. Please look through the history of closed issues for the reasoning why.

https://github.com/sodiumoxide/sodiumoxide/pull/361#issuecomment-519459157
