### ISSUE TITLE
Cross compiling targeting 32-bit Windows on 64-bit Windows fails

### ISSUE THREAD

**Issue by eliaslevy** [sodiumoxide/sodiumoxide#415]
I have a project that makes use of this crate.  Compiling on a 64-bit Windows 10 host targeting `x86_64-pc-windows-msvc` succeeds.  Trying to cross compile on the same host targeting `i686-pc-windows-msvc` fails.

```
> rustup show active-toolchain
stable-x86_64-pc-windows-msvc (default)

> rustup target list --installed
i686-pc-windows-msvc
x86_64-pc-windows-msvc

> cargo test --target i686-pc-windows-msvc
...
  = note: liblibsodium_sys-0ec9d10b60faaad4.rlib(sign.obj) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

error: aborting due to previous error
```

**Comment by eliaslevy** [comment]
Looks for some reason the wrong architecture is being picked when configuring the library path:
```
"/LIBPATH:C:\\Users\\Build\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libsodium-sys-0.2.5\\msvc/x64/Debug/v140/"
```

**Comment by kpp** [comment]
It is a known bug listed in https://github.com/sodiumoxide/sodiumoxide/issues/377

**Comment by eliaslevy** [comment]
Thanks.  I should have found that issue.  Apologies.  Closing.
