### ISSUE TITLE
Is `pwhash_verify` constant-time comparison?

### ISSUE THREAD

**Issue by maxcountryman** [sodiumoxide/sodiumoxide#423]
Glancing at the code, I'm not exactly sure how e.g. `argon2id13::pwhash_verify` is doing its comparison and if that comparison is constant-time.

**Comment by adamreichold** [comment]
This API just forwards to libsodium's verification function documented here: https://doc.libsodium.org/password_hashing/default_phf#password-storage

Sadly, this is not documented there either, but looking up libsodium's implementation shows that `sodium_memcmp` is used to check the final hash and this is a constant-time implementation:
* [`crypto_pwhash_argon2id_str_verify`](https://github.com/jedisct1/libsodium/blob/d1d777532fecc42a2e04f7bca3ec43f4481921c2/src/libsodium/crypto_pwhash/argon2/pwhash_argon2id.c#L226) calls `argon2id_verify`
* [`argon2id_verify`](https://github.com/jedisct1/libsodium/blob/d1d777532fecc42a2e04f7bca3ec43f4481921c2/src/libsodium/crypto_pwhash/argon2/argon2.c#L277) calls `argon2_verify`
* [`argon2_verify`](https://github.com/jedisct1/libsodium/blob/d1d777532fecc42a2e04f7bca3ec43f4481921c2/src/libsodium/crypto_pwhash/argon2/argon2.c#L259) calls `sodium_memcmp`
* That is a constant-time implementation of `memcmp`: https://doc.libsodium.org/helpers#constant-time-test-for-equality

**Comment by maxcountryman** [comment]
Thank you for the detailed answer! Most appreciated. 🙂
