### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tasn** [sodiumoxide/sodiumoxide#424]
Hey,

Thanks for the great work on this! There has been a few new features merged in to master since the last release. For example exposing `base64` and `kdf`. Would it be possible to make a new release so we can start using them?

Thanks,
Tom

**Comment by kpp** [comment]
Yes. Can you fill CHANGELOG and bump versions?

**Comment by tasn** [comment]
Sure, I can help with that. Do you have a script to generate the changelog from the commit messages or are you doing it manually? In addition, do you just put everything in the changelog, or only some of the changes, if some, how can I decide what to put and what not?
Btw, what version should this be? Should I bump minor or micro?

I'm sorry for all the questions, it's just hard to know what's the process like in this project as I'm not its maintainer. :)

**Comment by kpp** [comment]
I did it manually. I mentioned only significant changes and fixes. You can do it on your own, putting down meaningful titles of PRs.

**Comment by tasn** [comment]
Done in #425. I hope it's OK.

Though I just realised this lib doesn't support the Ed25519 to Curve25519 key conversion functions, so I may not be able to use it. :|

**Comment by kpp** [comment]
Thats right. This conversion is not supported by libsodium

**Comment by sbillig** [comment]
@tasn you can use the (unsafe) crypto_sign_ed25519_pk_to_curve25519 and crypto_sign_ed25519_sk_to_curve25519 functions from the libsodium-sys crate.

**Comment by tasn** [comment]
@sbillig, thanks for the tip!

P.S, I'm closing this ticket as a new version has been released.
