### ISSUE TITLE
Is sodiumoxide production ready or should I wait until a 1.x release ?

### ISSUE THREAD

**Issue by elovin** [sodiumoxide/sodiumoxide#433]
I`m new to rust and coming from php (which has libsodium bindings built in) I would like to use this project,
however, the version of the latest release makes me hesitant to use this project in production.

Would you say that sodiumoxide is production ready ?

**Comment by dnaq** [comment]
Yes. The reason for the 0.x version is that we probably want to add better error types to the api.
