### ISSUE TITLE
release a new version to crates.io ?

### ISSUE THREAD

**Issue by gcxfd** [sodiumoxide/sodiumoxide#457]
I saw [Added ed25519 to x25519 conversion methods](https://github.com/sodiumoxide/sodiumoxide/pull/456
) is merged 

When will release a new version to crates.io ?

**Comment by Rulliam** [comment]
Yeah, I would need a new libsodium-sys release on crates.io too

Thank you !

**Comment by nlfiedler** [comment]
Also it seems that since the 0.2.6 release, building on `aarch64-apple-darwin` is now successful.

**Comment by kpcyrd** [comment]
@Dylan-DPC @kpp who's currently able to push releases? :)

**Comment by dnaq** [comment]
I can push a new release if everything will be prepared for it

**Comment by kpcyrd** [comment]
What are the necessary steps to prepare a release?

**Comment by dnaq** [comment]
Merging anything that needs to be merged, bumping all deps that need to be
bumped (e.g libsodium), updating the change log and version numbers.

**Comment by ValHeimer** [comment]
> Merging anything that needs to be merged, bumping all deps that need to be bumped (e.g libsodium), updating the change log and version numbers.

I don't think we should merge anything more for the next release, there already is a ton of improvements and fixes available in master (6 months of commits) which are not released yet.

I even think we should not bump any deps in this release (0.2.7), even libsodium submodule (significant changes should be avoided, master branch was months tested by most of us and should be released as is, as it should have been some months ago). We will be able to bump everything in the next release (maybe 0.2.8).

If you agree with that @dnaq , I can create a pull request to bump sodiumoxide and libsodium-sys to 0.2.7 , and update the change log and version numbers

And then we can think about the changes for the next release (0.2.8).

**Comment by dnaq** [comment]
I'm ok with that. @kpp?

**Comment by dnaq** [comment]
I'm ok with that. @kpp?

**Comment by ValHeimer** [comment]
for example, https://github.com/sodiumoxide/sodiumoxide/pull/465 (bump libsodium submodule and binaries) opened by @tomstoneham should be merged after 0.2.7 is released (for 0.2.8)
