### ISSUE TITLE
Need a better documentation for new_type macro

### ISSUE THREAD

**Issue by basavesh** [sodiumoxide/sodiumoxide#458]
Hello,

Could you please improve the documentation for new_type macro? like what kind of traits "secret", "public" and "nonce" implements and what operations are not allowed on these types.

**Comment by dnaq** [comment]
The new_type macro is an implementation detail of the library and not a
part of the public API.

**Comment by basavesh** [comment]
I understand. Does it preserve constant-time guarantees? I need these information as I intend to use in a high-assurance cryptography project.

**Comment by brycx** [comment]
(Disclaimer: not a maintainer)

The newtype macros don't implement the actual functions supposed to run in constant-time. The macros are most often used to just reduce boilerplate code. 

In case of sodiumoxide, the macros are used, among other things, to ensure all types implement constant-time operations where needed.

Anyone from the org, please correct me if I'm wrong.
