### ISSUE TITLE
Poorly Documented Difference in Default pwhash Algorithm Choice from libsodium

### ISSUE THREAD

**Issue by tomstoneham** [sodiumoxide/sodiumoxide#462]
Hi! libsodium uses Argon 2 as the default hash function exposed by its `crypto_pwhash` API. For example, `crypto_pwhash(...)` and `crypto_pwhash_str(...)` output hashes calculated using Argon 2, and `crypto_pwhash_str_verify(...)` will [only verify Argon 2 hashes](https://github.com/jedisct1/libsodium/blob/ca638d42/src/libsodium/crypto_pwhash/crypto_pwhash.c#L174).

On the other hand, sodiumoxide exposes `crypto::pwhash::scryptsalsa208sha256` (Scrypt) as its de-facto "default" hash function in its `crypto::pwhash` API. Consider that `crypto::pwhash::derive_key(...)` (equivalent to libsodium's `crypto_pwhash(...)`) and `crypto::pwhash::pwhash(...)` (roughly equivalent to libsodium's `crypto_pwhash_str`) calculate hashes with Scrypt, and `crypto::pwhash::pwhash_verify(...)` uses libsodium's `crypto_pwhash_scryptsalsa208sha256_str_verify` internally, which will [only verify Scrypt hashes](https://github.com/jedisct1/libsodium/blob/ca638d42/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c#L243).

I totally appreciate the potential reasoning behind using Scrypt as the default hashing algorithm. As I understand it, it is considered a more conservative choice than Argon. My concern is just that this violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): If I hash a password using libsodium's `crypto_pwhash_str`, I would then be confused if a binding to libsodium fails to verify the password using `crypto::pwhash::pwhash_verify`. This is compounded by the fact that the [documentation for the `crypto::pwhash` API](https://docs.rs/sodiumoxide/0.2.6/sodiumoxide/crypto/pwhash/index.html) does not explicitly mention the default algorithm is different to the default algorithm in libsodium bindings for other languages.

As I see it, there are two reasonable solutions to the confusing situation:
* Change to use Argon 2id as the default: This would be less surprising for people new to the sodiumoxide binding, but familiar with libsodium. This would be a breaking change to the sodiumoxide API.
* Improve the documentation to clarify the difference: This would not require any breaking API changes, and if you have security reasons for preferring Scrypt as the default, this would preserve that.

I'm happy to put together a PR for either solution if you agree it's an issue :) Cheers!

**Comment by dnaq** [comment]
Hi,

I’m not that active as a maintainer anymore, other people have taken up the
mantle but I’ll just chime in to say that the main reason is that scrypt is
default is that it was the only pbkdf in libsodium at the time. Argon
support was added much later.

I wouldn’t say that scrypt is a more conservative choice. It’s older and
doesn’t have any known issues, but argon has won a competition.
